spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dto
    username: postgres
    password: nurlan21

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 1212

  error:
    include-stacktrace: always
